name: flutter_netflix_responsive_ui
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  stacked: ^1.7.6

  # Inversion of Control
  get_it: ^4.0.4
  injectable: ^1.0.4

  cupertino_icons: ^0.1.3
  video_player: ^0.10.12
  animations: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.2
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
